### PR TITLE
Events

### PR DESCRIPTION
**Pull request by kevana**

### CODE REVIEW

**Comment by crosbymichael** [comment]
i'll review soon

**Comment by kevana** [comment]
Right now it grabs everything from the last 24 hours, might be nice to change the time range, filter by event-type, link to image/container ID.

**Comment by kevana** [comment]
Current implementation isn't very testable, may look into [extracting oboe to a service](http://stackoverflow.com/a/25582078/2811887) in the future.

**Comment by kevana** [comment]
* Added view for events
* Cleaned up storage driver status display
* Upgraded to Angular 1.3.15

**Pull request merged**
