### PR TITLE
Container logs module

### PR DESCRIPTION
**Pull request by kevana**
Many thanks to @KLINGTdotNET in #43 for doing the work. After the big refactoring their PR wasn't auto-mergeable so I put that work into the new module format.

### CODE REVIEW

**Comment by jonny64** [comment]
I've been running container for about two months, logs are huge, logs page loads too slow.
Let's say, I want just last 2000 lines
How it is possible to limit log output? docker 1.3 includes --tail=count_lines_to_show
I can and willing to contribute, how log output limit should work? A settings maybe?
I suggest default log limit to last 2000 lines

**Comment by kevana** [comment]
I think the easiest way would be to default to 2000 and expose the `tail` option on the logs page to let people change it.

**Comment by jonny64** [comment]
what is the easiest way to create dev enviroment? this wasn't mentioned in readme
is `grunt build` enough?
i've got web part working, but it can't connect to docker api

**Comment by jonny64** [comment]
https://github.com/crosbymichael/dockerui/pull/77

**Pull request merged**
