### PR TITLE
Fix the image name not show issue

### PR DESCRIPTION
**Pull request by HackToday**
Closes-Issue: #87

1. This fixed the issue of image name not show correctly.
2 . Also help fix in main page images link, the tag field can not be input any text.

### CODE REVIEW

**Comment by HackToday** [comment]
This not fix the dockerui known issue, for tag, only have one field, to add tag.
But in docker API. 

https://docs.docker.com/reference/api/docker_remote_api_v1.18/

Tag an image into a repository
POST /images/(name)/tag

Tag the image name into a repository

Example request:

    POST /images/test/tag?repo=myrepo&force=0&tag=v42 HTTP/1.1
Example response:

    HTTP/1.1 201 OK
Query Parameters:

repo – The repository to tag in
force – 1/True/true or 0/False/false, default false
tag - The new tag name


It need repo and tag field. But we only update repo and force, dockerui not support update tag name now. It is a new issue, So need other patch to fix that.  I think

**Comment by kevana** [comment]
An option for a more robust solution that doesn't rely on a query param in the URL is to get the RepoTags from the images list. It's an extra ajax call, but it will always work. In its current state if a user clicks on a parent image link the repo won't be shown. Also, we might want to only display repo on the page.

screen shot 2015-05-06 at 4 01 26 pm

Good catch on the tag updating, I opened #113 for it.

**Comment by HackToday** [comment]
@kevana 

1. seems the parent image repo can not be get from docker API /images/{id}/json

2. And you suggest, in container page, if we click image link, we fetch the repo from /images docker API ?

**Comment by kevana** [comment]
Correct, links to an image can come from a container page, image list, or other image pages, we should try to find a solution that works for all of those.

**Comment by kevana** [comment]
Fixed by #155

**Pull request closed without merging**
