### PR TITLE
Added restart to container list actions.

### PR DESCRIPTION
**Pull request by kevana**
Related to #78

### CODE REVIEW

**Comment by kevana** [comment]
This should be good to go.

**Comment by Slamper** [comment]
Does the restart method require the hostconfig ?  In that case we would have to add "|| action === Container.restart"  to the check implemented in #79  so the hostconfig wouldn't be removed on restart.

**Comment by kevana** [comment]
The Remote API docs indicate that it doesn't, but it wouldn't surprise me if it did, I'll do more testing tonight.

**Comment by kevana** [comment]
I just checked, containers do maintain their HostConfig when restarted.

**Pull request merged**
