### PR TITLE
DockerUI - Linking correct API Doc

### PR DESCRIPTION
**Pull request by BrockFredin**
Updating the link.  The one in the active comment is a broken link.  Thanks!

### CODE REVIEW

**Comment by kevana** [comment]
There's other broken links in comments on lines 59, 75, 83, and 92, as long as you're there could you update them?

**Comment by BrockFredin** [comment]
I updated the comments for each of the page numbers.  Thanks!

**Comment by kevana** [comment]
Latest remote API is `v1.18`, not sure if there's a url that always points to the latest version.

**Comment by BrockFredin** [comment]
Changed app.js to reflect v1.18.  Is there a standardized 'ui_version'.  Because that would also need to be changed.

**Comment by kevana** [comment]
Don't worry about ui_version, I bump that before releases. I meant the links are pointing to an old version of the docs, 12, not 18.

    https://docs.docker.com/reference/api/docker_remote_api_v1.12

**Comment by kevana** [comment]
Fixed by abccb31

**Pull request closed without merging**
